# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - name: Fix Permissions
      run: sudo chown -R $USER:$USER /home/admin/actions-runner/_agresen/server || true

    - uses: actions/checkout@v4
      with:
        clean: false # Prevents checkout from deleting node_modules

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Ensure Correct Permissions on node_modules
      run: sudo chmod -R 777 node_modules || true

    - run: npm ci

    - run: |
        touch .env
        echo "$({secrets.PROD})" > .env

    - run: pm2 restart agresenBackend

